# Generated by Django 6.0.2 on 2026-02-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='icon',
            field=models.CharField(default='Book', max_length=50),
        ),
    ]
