# Generated by Django 6.0.2 on 2026-02-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='deck',
        ),
        migrations.AddField(
            model_name='deck',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.folder'),
        ),
    ]
