# Generated by Django 6.0.2 on 2026-02-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_deck_created_at_remove_deck_icon_folder_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='icon',
            field=models.CharField(default='Folder', max_length=50),
        ),
    ]
