# Generated by Django 6.0.2 on 2026-02-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_folder_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='icon',
        ),
        migrations.AddField(
            model_name='deck',
            name='icon',
            field=models.CharField(default='Book', max_length=50),
        ),
    ]
