# Generated by Django 6.0.2 on 2026-02-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_studysession_userstats_cardperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='daily_budget_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='deck',
            name='target_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
