# Generated by Django 6.0.2 on 2026-03-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_deck_daily_budget_minutes_deck_target_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='difficulty_multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
