# Generated by Django 6.0.2 on 2026-03-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_tag_deck_is_public_deck_original_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
