# Generated by Django 6.0.2 on 2026-03-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_deck_share_count_deck_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
